### ISSUE TITLE
Mining Software

### ISSUE THREAD

**Issue by BurntRouter** [Aareon/chickenticket#15]
Since we're losers and like to use Python, how we're doing this whole thing won't use Allium like C does so it will more than likely not be compatible with current miners which means we'll have to write our own. Hopefully the community will help out with this after launch.

Will support:
CUDA probably 8.0+
OpenCL probably 1.1
CPU better have a ton of xeons homie

**Comment by Aareon** [comment]
We are using Allium, its simply not implemented right now in a way that is compatible with current miners. I will look into trying to implement it so that we *can* use the current miners, but we might have to write our own. Hopefully it doesn't come to that.

**Comment by BurntRouter** [comment]
"Hopefully it doesn't come to that." 👍 with that one. Might want to bring in community help on this one

**Comment by Aareon** [comment]
Settled on using a different hashing algorithm (likely blake2s)
