### ISSUE TITLE
Screenshot in your readme 

### ISSUE THREAD

**Issue by PySimpleGUI** [Aareon/ChickenTicket#37]
I see you've got a GUI either already running or about to be running.  

I, and your other visitors, would love ![image](https://user-images.githubusercontent.com/46163555/167264812-8d85b809-798f-4254-b307-e6fd61f4ccd4.png) to see an image of what you make!  

![image](https://user-images.githubusercontent.com/46163555/167264860-1d369e43-bc7e-4553-990a-09ef1e8ee964.png)

**Comment by Aareon** [comment]
I’ll prop it up when I’m on break! The main wallet window is still being implemented but the design is mostly there. Been doing some research on `Col` to display recent transactions, but I don’t mind showing what I’ve got so far.

**Comment by PySimpleGUI** [comment]
No rush at all... was just a suggestion for whenever is appropriate.  You've clearly put in a bunch of time making a GUI... want to see you enjoy sharing it with others.  We all like pictures!  OK, I'll also admit that _**I**_ like pictures.  It's fun to see what's being made.
![image](https://user-images.githubusercontent.com/46163555/167266496-6b723332-cf8f-4f6a-8e21-5a7018e8ff23.png)

**Comment by PySimpleGUI** [comment]
https://github.com/Aareon/ChickenTicket/blob/6ae39b0e5f15cf4080996880dce55ca85eb2f8ae/src/simplegui.py#L352

And... wow... using User Settings!  I'm impressed... glad to see it's being used by others than me.

**Comment by Aareon** [comment]
@PySimpleGUI check the README now. Definitely could look better, but its functional.

**Comment by Aareon** [comment]
Thanks for showing interest! I'm super passionate about making everything robust and user friendly.

**Comment by PySimpleGUI** [comment]
OMG!  I had no clue you had so many windows in your app!

![image](https://user-images.githubusercontent.com/46163555/167266885-c31e3784-aa6e-4759-8529-9ae00fb15536.png)

VERY NICE!  Now it's clear you've got a substantial application going!


> its functional

This.... this is the most important part in the end.  It's gotta work or it's all for naught.

**Comment by Aareon** [comment]
@PySimpleGUI bunch more dialogs added to screenshots. They all play nicely with one another.

**Comment by PySimpleGUI** [comment]
I'm sure they do play well together.  
![image](https://user-images.githubusercontent.com/46163555/167267162-49a5d2cb-489e-4bd3-9329-8d0a616b5d51.png)

It's clear you're paying attention to the details, being purposeful in your approach, and not just throwing stuff together.

**Comment by Aareon** [comment]
@PySimpleGUI if you see anything and want to provide input or suggestions, I'd be more than happy to accept critiques. I appreciate your suggestion. I'm gonna close this issue now and chalk this up as accomplished. Thanks for the suggestion!

**Comment by PySimpleGUI** [comment]
Yea yea!  Close it out!

![image](https://user-images.githubusercontent.com/46163555/167267727-7fdea810-7cbd-487d-8270-ea088a2ad62d.png)

Don't want stuff sitting open in Issues that are distracting and not actually active.  See.. proof there of what I said.... you're paying attention to details.

Thanks for adding them and the fun conversation.  Keep building!  You're kicking *ss!
