### ISSUE TITLE
Error when running wallet launch command. 

### ISSUE THREAD

**Issue by NewtonJr4108** [Aareon/ChickenTicket#44]
On MacOS, when following Unix command, I get this error:

`python3 src/simplegui.py
2023-04-18 10:00:47.194 Python[60564:1744359] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8099531ba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80947942b objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80997b316 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x00007ff80c9933ef -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 307
	4   AppKit                              0x00007ff80c97f8e4 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1227
	5   AppKit                              0x00007ff80c97f412 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libtk8.6.dylib                      0x0000000102e84f91 TkMacOSXMakeRealWindowExist + 720
	7   libtk8.6.dylib                      0x0000000102e84b93 TkWmMapWindow + 63
	8   libtk8.6.dylib                      0x0000000102dea125 Tk_MapWindow + 158
	9   libtk8.6.dylib                      0x0000000102df2a8b MapFrame + 59
	10  libtcl8.6.dylib                     0x0000000102528171 TclServiceIdle + 75
	11  libtcl8.6.dylib                     0x000000010250c796 Tcl_DoOneEvent + 341
	12  libtk8.6.dylib                      0x0000000102e77716 TkpInit + 766
	13  libtk8.6.dylib                      0x0000000102deb387 Initialize + 2402
	14  _tkinter.cpython-310-darwin.so      0x000000010224f6bb Tcl_AppInit + 91
	15  _tkinter.cpython-310-darwin.so      0x000000010224f3a9 Tkapp_New + 585
	16  _tkinter.cpython-310-darwin.so      0x000000010224f14e _tkinter_create_impl + 222
	17  _tkinter.cpython-310-darwin.so      0x000000010224ed74 _tkinter_create + 164
	18  Python                              0x00000001027181a6 cfunction_vectorcall_FASTCALL + 86
	19  Python                              0x00000001027f243f call_function + 175
	20  Python                              0x00000001027e87ea _PyEval_EvalFrameDefault + 24122
	21  Python                              0x00000001027e103f _PyEval_Vector + 383
	22  Python                              0x00000001026b0900 _PyObject_FastCallDictTstate + 96
	23  Python                              0x0000000102745b59 slot_tp_init + 201
	24  Python                              0x000000010273c3e2 type_call + 322
	25  Python                              0x00000001026b0674 _PyObject_MakeTpCall + 132
	26  Python                              0x00000001027f24fd call_function + 365
	27  Python                              0x00000001027e87ea _PyEval_EvalFrameDefault + 24122
	28  Python                              0x00000001027e103f _PyEval_Vector + 383
	29  Python                              0x00000001027f243f call_function + 175
	30  Python                              0x00000001027e8831 _PyEval_EvalFrameDefault + 24193
	31  Python                              0x00000001027e103f _PyEval_Vector + 383
	32  Python                              0x00000001027f243f call_function + 175
	33  Python                              0x00000001027e8831 _PyEval_EvalFrameDefault + 24193
	34  Python                              0x00000001027e103f _PyEval_Vector + 383
	35  Python                              0x00000001027f243f call_function + 175
	36  Python                              0x00000001027e875d _PyEval_EvalFrameDefault + 23981
	37  Python                              0x00000001027e103f _PyEval_Vector + 383
	38  Python                              0x00000001026b472f method_vectorcall + 159
	39  Python                              0x00000001027f243f call_function + 175
	40  Python                              0x00000001027e88ec _PyEval_EvalFrameDefault + 24380
	41  Python                              0x00000001027e103f _PyEval_Vector + 383
	42  Python                              0x00000001027f243f call_function + 175
	43  Python                              0x00000001027e875d _PyEval_EvalFrameDefault + 23981
	44  Python                              0x00000001027e103f _PyEval_Vector + 383
	45  Python                              0x00000001027f243f call_function + 175
	46  Python                              0x00000001027e87ea _PyEval_EvalFrameDefault + 24122
	47  Python                              0x00000001027e103f _PyEval_Vector + 383
	48  Python                              0x00000001027f243f call_function + 175
	49  Python                              0x00000001027e875d _PyEval_EvalFrameDefault + 23981
	50  Python                              0x00000001027e103f _PyEval_Vector + 383
	51  Python                              0x00000001027e8f29 _PyEval_EvalFrameDefault + 25977
	52  Python                              0x00000001027e103f _PyEval_Vector + 383
	53  Python                              0x00000001027f243f call_function + 175
	54  Python                              0x00000001027e875d _PyEval_EvalFrameDefault + 23981
	55  Python                              0x00000001027e103f _PyEval_Vector + 383
	56  Python                              0x00000001027f243f call_function + 175
	57  Python                              0x00000001027e875d _PyEval_EvalFrameDefault + 23981
	58  Python                              0x00000001027e103f _PyEval_Vector + 383
	59  Python                              0x00000001026b4871 method_vectorcall + 481
	60  Python                              0x00000001028e8b36 thread_run + 198
	61  Python                              0x000000010286bb84 pythread_wrapper + 36
	62  libsystem_pthread.dylib             0x00007ff8098001d3 _pthread_start + 125
	63  libsystem_pthread.dylib             0x00007ff8097fbbd3 thread_start + 15
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      python3 src/simplegui.py
`

**Comment by NewtonJr4108** [comment]
I've run this successfully on Windows, so this may just be unique to Mac.

**Comment by Aareon** [comment]
This traceback is unique to Mac, but the main issue is my usage of threads. I'll rewrite the wallet using PySide6 (Qt).

**Comment by Aareon** [comment]
This issue is no longer relevant as the associated files have been deleted
