### ISSUE TITLE
Error running simplegui.py

### ISSUE THREAD

**Issue by NewtonJr4108** [Aareon/chickenticket#56]
I used the command to run the gui program and I got the following error (running on Mac so this may be some compatibility issue but it also my be a threading problem):

`DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2024-03-29 23:50:20.583 Python[17510:456376] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8180a911a __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff817bcf0b7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8180d1296 -[NSException raise] + 9
	3   AppKit                              0x00007ff81b0f4d2e -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 307
	4   AppKit                              0x00007ff81b0e1244 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1227
	5   AppKit                              0x00007ff81b0e0d72 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   Tk                                  0x00007ffb1cec139f TkMacOSXMakeRealWindowExist + 604
	7   Tk                                  0x00007ffb1cec2554 TkMacOSXUnregisterMacWindow + 2126
	8   Tk                                  0x00007ffb1cec1f86 TkMacOSXUnregisterMacWindow + 640
	9   Tcl                                 0x00007ffb1cd45398 Tcl_ListMathFuncs + 1765
	10  Tcl                                 0x00007ffb1cd45c0d Tcl_EvalObjv + 57
	11  _tkinter.cpython-39-darwin.so       0x0000000109d25a2c PyInit__tkinter + 5628
	12  Python3                             0x0000000109e59a1a PyDescr_NewMethod + 490
	13  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	14  Python3                             0x0000000109f2a5b6 _PyEval_EvalFrameDefault + 22998
	15  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	16  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	17  Python3                             0x0000000109e53a8f PyMethod_New + 367
	18  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	19  Python3                             0x0000000109f2a5d4 _PyEval_EvalFrameDefault + 23028
	20  Python3                             0x0000000109e51760 _PyFunction_Vectorcall + 512
	21  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	22  Python3                             0x0000000109f2a666 _PyEval_EvalFrameDefault + 23174
	23  Python3                             0x0000000109e51760 _PyFunction_Vectorcall + 512
	24  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	25  Python3                             0x0000000109f2a666 _PyEval_EvalFrameDefault + 23174
	26  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	27  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	28  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	29  Python3                             0x0000000109f2a5b6 _PyEval_EvalFrameDefault + 22998
	30  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	31  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	32  Python3                             0x0000000109e53a8f PyMethod_New + 367
	33  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	34  Python3                             0x0000000109f2a6f5 _PyEval_EvalFrameDefault + 23317
	35  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	36  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	37  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	38  Python3                             0x0000000109f2a5b6 _PyEval_EvalFrameDefault + 22998
	39  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	40  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	41  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	42  Python3                             0x0000000109f2a5d4 _PyEval_EvalFrameDefault + 23028
	43  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	44  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	45  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	46  Python3                             0x0000000109f2a5b6 _PyEval_EvalFrameDefault + 22998
	47  Python3                             0x0000000109f2eb4c _PyEval_EvalFrameDefault + 40812
	48  Python3                             0x0000000109e51665 _PyFunction_Vectorcall + 261
	49  Python3                             0x0000000109f2aa47 _PyEval_EvalFrameDefault + 24167
	50  Python3                             0x0000000109e51760 _PyFunction_Vectorcall + 512
	51  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	52  Python3                             0x0000000109f2a5b6 _PyEval_EvalFrameDefault + 22998
	53  Python3                             0x0000000109e51760 _PyFunction_Vectorcall + 512
	54  Python3                             0x0000000109f2da7b _PyEval_EvalFrameDefault + 36507
	55  Python3                             0x0000000109f2a5b6 _PyEval_EvalFrameDefault + 22998
	56  Python3                             0x0000000109e51760 _PyFunction_Vectorcall + 512
	57  Python3                             0x0000000109e53b18 PyMethod_New + 504
	58  Python3                             0x0000000109fc57d6 PyInit__thread + 5702
	59  Python3                             0x0000000109f783e9 PyThread_start_new_thread + 313
	60  libsystem_pthread.dylib             0x00007ff817f561d3 _pthread_start + 125
	61  libsystem_pthread.dylib             0x00007ff817f51bd3 thread_start + 15
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      /usr/bin/python3 simplegui.py
`

**Comment by Aareon** [comment]
Hey @NewtonJr4108! All new work is being done in the [develop branch](https://github.com/Aareon/ChickenTicket/tree/develop).  The `simplegui` wallet is deprecated. At this time, no wallet is as of yet ready to use. I'll update the README and make an announcement on Discord when that changes.

**Comment by NewtonJr4108** [comment]
Oh, got it! I'll use the devlop branch to test from now on.
