### ISSUE TITLE
Mining algorithm

### ISSUE THREAD

**Issue by Aareon** [Aareon/chickenticket#9]
We're shooting for the [Allium](https://github.com/JayDDee/cpuminer-opt/blob/master/algo/lyra2/allium.c) algorithm, which I believe @AnonymousDapper has made some progress on.

Extensive testing will be needed to verify that the algorithm is being used properly. The `genesis.py` transaction hash will also have to be changed from `SHA256` to `Allium`

**Comment by AnonymousDapper** [comment]
This should be complete with #11

**Comment by Aareon** [comment]
Will definitely need some tests. Eventually we'll get around to adding those.

**Comment by Aareon** [comment]
Opted out of in favor of Chicken (src/crypto/chicken.py)
